---
- name: Disable swap
  command: swapoff -a
  become: true

- name: Remove swap entry from fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*swap.*)$'
    replace: '# \1'
  become: true

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    update_cache: yes
  become: true

- name: Install containerd
  apt: 
    name: containerd
    state: present
  become: true

- name: Configure containerd
  shell: |
    mkdir -p /etc/containerd
    containerd config default > /etc/containerd/config.toml
    sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
  become: true

- name: Enable containerd
  systemd:
    name: containerd
    state: started
    enabled: true
  become: true

- name: Remove legacy Kubernetes apt repository file if present
  file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: absent
  become: true

- name: Ensure apt keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Add Kubernetes apt repository signing key (pkgs.k8s.io v1.34)
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  become: true

- name: Add Kubernetes apt repository (v1.34)
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /'
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install kubelet, kubeadm, kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: no
  become: true

- name: Enable kubelet service
  systemd:
    name: kubelet
    enabled: yes
    state: started
  become: true